/*
 * This source file was generated by the Gradle 'init' task
 */
package tool.migration;

import tool.migration.logging.AppLogger;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        AppLogger.info("testing");
    }
}
